/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md. A commercial
 * license (without AGPL source-disclosure terms) is available -
 * contact legal@dankest.llc.
 *
 **********************************************************************
 *
 * XChain Hub - public discovery routes: the chain registry and the OpenRPC spec.
 *
 ********************************************************************/

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

function mountRegistryRoutes(app, ctx) {
    mountChainRegistry(app, ctx);
    mountOpenrpcSpec(app);
}

// Public chain registry for wallet/SDK bootstrap (wallet spec G007 / §9.7).
// Serves the wallet-authored descriptor snapshot vendored at
// src/chain-registry.json (synced from the wallet's bundled descriptors by
// xchain-wallet/bin/sync-chain-registry.mjs; drift-guarded in CI). Public
// read tier by design: endpoint URLs + UX metadata only, no secrets. When
// this hub has a signing identity (validator mode) the response also
// carries an Ed25519 signature so clients can verify before merging:
//   signature = sign('XCHAIN_CHAIN_REGISTRY_V1|' + generated_at + '|' +
//                    sha256hex(JSON.stringify(descriptors)))
function mountChainRegistry(app, { hub }) {
    let chainRegistryCache = null;
    app.get('/api/v1/chain-registry', (req, res) => {
        try {
            if (!chainRegistryCache) {
                const raw = JSON.parse(fs.readFileSync(path.join(__dirname, '..', '..', 'chain-registry.json'), 'utf8'));
                const body = {
                    schema_version: raw.schema_version,
                    generatedAt:    raw.generated_at,
                    descriptors:    raw.descriptors
                };
                try {
                    const identity = hub.getIdentity ? hub.getIdentity() : null;
                    if (identity && identity.getPubkeyHex && identity.sign) {
                        const digest = crypto.createHash('sha256')
                            .update(JSON.stringify(raw.descriptors)).digest('hex');
                        body.signer_pubkey = identity.getPubkeyHex();
                        body.signature = identity.sign(
                            'XCHAIN_CHAIN_REGISTRY_V1|' + raw.generated_at + '|' + digest);
                    }
                } catch (e) { /* standalone hub: served unsigned */ }
                chainRegistryCache = body;
            }
            res.set('Cache-Control', 'public, max-age=300');
            // Public discovery surface consumed cross-origin by browser wallets
            // (web SPA + MV3 extension, which ships no host_permissions). The
            // global CORS_ORIGIN default stays off for everything else.
            res.set('Access-Control-Allow-Origin', '*');
            res.json(chainRegistryCache);
        } catch (err) {
            res.status(500).json({ error: 'chain registry unavailable' });
        }
    });
}

// Machine-readable API spec (OpenRPC 1.3.2). Regenerated by docs/openrpc.build.js;
// test/unit/api/openrpc_coverage.test.js keeps it in lockstep with jsonRpcController.
function mountOpenrpcSpec(app) {
    let openrpcSpec = null;
    app.get('/openrpc.json', (req, res) => {
        if (!openrpcSpec)
            openrpcSpec = fs.readFileSync(path.join(__dirname, '../../../docs/openrpc.json'));
        res.set('Cache-Control', 'public, max-age=3600');
        res.type('application/json').send(openrpcSpec);
    });
}

module.exports = { mountRegistryRoutes };
