CREATE TABLE consensus_state (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    key_name   VARCHAR(64) NOT NULL UNIQUE,
    value      TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
