/*********************************************************************
 *
 * Copyright © 2025-2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC - https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md. A commercial
 * license (without AGPL source-disclosure terms) is available -
 * contact legal@dankest.llc.
 *
 **********************************************************************
 *
 * XChain Hub - configuration
 *
 * The one module that names the environment. Every other module takes its
 * settings from the object exported here instead of reaching for process.env
 * itself, so the variables the hub reads have one declared inventory and one
 * place a reader looks them up.
 *
 * Each entry is a GETTER, so the value is read at use and not at load. That is
 * what makes the home safe to require from anywhere: it evaluates nothing when
 * it loads, so no module's boot order depends on it, and a suite that sets a
 * variable between requires still changes what the code under it sees. A
 * snapshot taken at load would have gone stale in 34 of this repo's own tests
 * without raising anything. The object is frozen, so no caller can change a
 * setting after boot.
 *
 * The DEFAULT stays at the read site, deliberately. Nearly every site reads
 * `env || cfg.NAME || '<default>'`, where cfg is the instance's own settings;
 * hoisting the literal into the getter would make that middle term unreachable
 * and silently change which setting wins. Hoisting them is a later pass, one
 * name at a time, against each site's precedence.
 *
 * The entries are GENERATED by the env-config codemod in its lazy mode, which
 * appends them after the anchor line. Two shapes have no single name to move: a
 * read under a computed key (`process.env[coin + '_INDEXER_URL']`) and a use of
 * the env OBJECT itself (`{ ...process.env }`, `env = env || process.env`). Both
 * go through `config.env()` below, which hands back the live environment object.
 *
 ********************************************************************/

'use strict';

const config = {
    // codemod:env-entries
    get DB_ACQUIRE_TIMEOUT() { return process.env.DB_ACQUIRE_TIMEOUT; },
    get DB_CONNECT_TIMEOUT() { return process.env.DB_CONNECT_TIMEOUT; },
    get DB_QUERY_TIMEOUT() { return process.env.DB_QUERY_TIMEOUT; },
    get ADMISSION_ORACLE_INGEST_WINDOW_MS() { return process.env.ADMISSION_ORACLE_INGEST_WINDOW_MS; },
    get ADMISSION_TIP_MAX_AGE_S() { return process.env.ADMISSION_TIP_MAX_AGE_S; },
    get ADMISSION_WATERMARK_SAMPLE_MS() { return process.env.ADMISSION_WATERMARK_SAMPLE_MS; },
    get ANCHOR_AMBIGUOUS_POLL_ATTEMPTS() { return process.env.ANCHOR_AMBIGUOUS_POLL_ATTEMPTS; },
    get ANCHOR_AMBIGUOUS_POLL_MS() { return process.env.ANCHOR_AMBIGUOUS_POLL_MS; },
    get ANCHOR_ANNOUNCE_QUEUE_MAX() { return process.env.ANCHOR_ANNOUNCE_QUEUE_MAX; },
    get ANCHOR_ANNOUNCE_RETRY_MS() { return process.env.ANCHOR_ANNOUNCE_RETRY_MS; },
    get ANCHOR_ANNOUNCE_RETRY_TTL_MS() { return process.env.ANCHOR_ANNOUNCE_RETRY_TTL_MS; },
    get ANCHOR_CHECKPOINT_EVERY_N() { return process.env.ANCHOR_CHECKPOINT_EVERY_N; },
    get ANCHOR_CHUNK_MAX_BYTES() { return process.env.ANCHOR_CHUNK_MAX_BYTES; },
    get ANCHOR_CHUNK_RETRY_MS() { return process.env.ANCHOR_CHUNK_RETRY_MS; },
    get ANCHOR_CONFIRM_CHECK_MS() { return process.env.ANCHOR_CONFIRM_CHECK_MS; },
    get ANCHOR_CONFIRM_STALE_MS() { return process.env.ANCHOR_CONFIRM_STALE_MS; },
    get ANCHOR_ELECTION_TOLERANCE_BLOCKS() { return process.env.ANCHOR_ELECTION_TOLERANCE_BLOCKS; },
    get ANCHOR_ENABLED() { return process.env.ANCHOR_ENABLED; },
    get ANCHOR_INTENT_TTL_MS() { return process.env.ANCHOR_INTENT_TTL_MS; },
    get ANCHOR_INTERVAL_MS() { return process.env.ANCHOR_INTERVAL_MS; },
    get ANCHOR_MARKER_RETENTION_MS() { return process.env.ANCHOR_MARKER_RETENTION_MS; },
    get ANCHOR_MATCH_BATCH_SIZE() { return process.env.ANCHOR_MATCH_BATCH_SIZE; },
    get ANCHOR_MAX_BATCH() { return process.env.ANCHOR_MAX_BATCH; },
    get ANCHOR_PUBLISH_ALLOW_UNCONFIRMED_INPUTS() { return process.env.ANCHOR_PUBLISH_ALLOW_UNCONFIRMED_INPUTS; },
    get ANCHOR_RANK_WAKE_MS() { return process.env.ANCHOR_RANK_WAKE_MS; },
    get ANCHOR_RATELIMIT_MAX_WAITS() { return process.env.ANCHOR_RATELIMIT_MAX_WAITS; },
    get ANCHOR_RATELIMIT_MAX_WAIT_MS() { return process.env.ANCHOR_RATELIMIT_MAX_WAIT_MS; },
    get ANCHOR_REWARD_PER_PUBLISH() { return process.env.ANCHOR_REWARD_PER_PUBLISH; },
    get ANCHOR_ROUND_TIMEOUT_MS() { return process.env.ANCHOR_ROUND_TIMEOUT_MS; },
    get ANCHOR_STARTUP_FLUSH_MS() { return process.env.ANCHOR_STARTUP_FLUSH_MS; },
    get ATTESTATION_AMBIGUOUS_COOLDOWN_MS() { return process.env.ATTESTATION_AMBIGUOUS_COOLDOWN_MS; },
    get ATTESTATION_BLOCK_MS() { return process.env.ATTESTATION_BLOCK_MS; },
    get ATTESTATION_FAILOVER_POLL_MS() { return process.env.ATTESTATION_FAILOVER_POLL_MS; },
    get ATTESTATION_FAILOVER_WINDOW_BLOCKS() { return process.env.ATTESTATION_FAILOVER_WINDOW_BLOCKS; },
    get ATTESTATION_HTTP_GET_ALLOW_PRIVATE() { return process.env.ATTESTATION_HTTP_GET_ALLOW_PRIVATE; },
    get ATTESTATION_LEADER_RETRY_MS() { return process.env.ATTESTATION_LEADER_RETRY_MS; },
    get ATTESTATION_POLL_MS() { return process.env.ATTESTATION_POLL_MS; },
    get ATTESTATION_QUEUE_PATH() { return process.env.ATTESTATION_QUEUE_PATH; },
    get ATTESTATION_ROUND_TIMEOUT_MS() { return process.env.ATTESTATION_ROUND_TIMEOUT_MS; },
    get ATTESTATION_TIMEOUT() { return process.env.ATTESTATION_TIMEOUT; },
    get ATTEST_BATCH_BUFFER_PATH() { return process.env.ATTEST_BATCH_BUFFER_PATH; },
    get ATTEST_BATCH_MAX_REFUSAL_ATTEMPTS() { return process.env.ATTEST_BATCH_MAX_REFUSAL_ATTEMPTS; },
    get ATTEST_BATCH_PUBLISH_ENABLED() { return process.env.ATTEST_BATCH_PUBLISH_ENABLED; },
    get ATTEST_BATCH_WINDOW_S_OVERRIDE() { return process.env.ATTEST_BATCH_WINDOW_S_OVERRIDE; },
    get ATTEST_ENABLED() { return process.env.ATTEST_ENABLED; },
    get ATTEST_PUBLISHED_REQUESTS_RETENTION_MS() { return process.env.ATTEST_PUBLISHED_REQUESTS_RETENTION_MS; },
    get ATTEST_RELAY_ENABLED() { return process.env.ATTEST_RELAY_ENABLED; },
    get ATTEST_RELAY_EVICT_GRACE_BLOCKS() { return process.env.ATTEST_RELAY_EVICT_GRACE_BLOCKS; },
    get ATTEST_RELAY_FAILOVER_MS() { return process.env.ATTEST_RELAY_FAILOVER_MS; },
    get ATTEST_RELAY_POLL_MS() { return process.env.ATTEST_RELAY_POLL_MS; },
    get ATTEST_RELAY_QUEUE_PATH() { return process.env.ATTEST_RELAY_QUEUE_PATH; },
    get ATTEST_RESPONSE_FORWARD_S_OVERRIDE() { return process.env.ATTEST_RESPONSE_FORWARD_S_OVERRIDE; },
    get BTC_ADDRESS() { return process.env.BTC_ADDRESS; },
    get BTC_ENCODER_API_KEY() { return process.env.BTC_ENCODER_API_KEY; },
    get BTC_ENCODER_URL() { return process.env.BTC_ENCODER_URL; },
    get BTC_INDEXER_API_KEY() { return process.env.BTC_INDEXER_API_KEY; },
    get BTC_INDEXER_API_URL() { return process.env.BTC_INDEXER_API_URL; },
    get BTC_INDEXER_URL() { return process.env.BTC_INDEXER_URL; },
    get BTC_PUBKEY_HEX() { return process.env.BTC_PUBKEY_HEX; },
    get CHECKPOINT_CHAINS() { return process.env.CHECKPOINT_CHAINS; },
    get CHECKPOINT_CONFIRMATIONS() { return process.env.CHECKPOINT_CONFIRMATIONS; },
    get CHECKPOINT_COSIGN_TOLERANCE_BLOCKS() { return process.env.CHECKPOINT_COSIGN_TOLERANCE_BLOCKS; },
    get CHECKPOINT_ENABLED() { return process.env.CHECKPOINT_ENABLED; },
    get CHECKPOINT_FROZEN_TIP_TICKS() { return process.env.CHECKPOINT_FROZEN_TIP_TICKS; },
    get CHECKPOINT_INTERVAL_BLOCKS() { return process.env.CHECKPOINT_INTERVAL_BLOCKS; },
    get CHECKPOINT_POLL_MS() { return process.env.CHECKPOINT_POLL_MS; },
    get CHECKPOINT_ROUND_TIMEOUT_MS() { return process.env.CHECKPOINT_ROUND_TIMEOUT_MS; },
    get CHECKPOINT_STALL_LOG_MS() { return process.env.CHECKPOINT_STALL_LOG_MS; },
    get CLAUDE_BIN() { return process.env.CLAUDE_BIN; },
    get COINGECKO_API_KEY() { return process.env.COINGECKO_API_KEY; },
    get COINMARKETCAP_API_KEY() { return process.env.COINMARKETCAP_API_KEY; },
    get CORS_ORIGIN() { return process.env.CORS_ORIGIN; },
    get CROSS_CHAIN_INDEXER_TIMEOUT() { return process.env.CROSS_CHAIN_INDEXER_TIMEOUT; },
    get DOGE_ADDRESS() { return process.env.DOGE_ADDRESS; },
    get DOGE_ENCODER_API_KEY() { return process.env.DOGE_ENCODER_API_KEY; },
    get DOGE_ENCODER_URL() { return process.env.DOGE_ENCODER_URL; },
    get DOGE_INDEXER_API_KEY() { return process.env.DOGE_INDEXER_API_KEY; },
    get DOGE_INDEXER_API_URL() { return process.env.DOGE_INDEXER_API_URL; },
    get DOGE_INDEXER_URL() { return process.env.DOGE_INDEXER_URL; },
    get DOGE_LOW_BALANCE_THRESHOLD() { return process.env.DOGE_LOW_BALANCE_THRESHOLD; },
    get DOGE_PUBKEY_HEX() { return process.env.DOGE_PUBKEY_HEX; },
    get FULLNODE_BTC_RPC() { return process.env.FULLNODE_BTC_RPC; },
    get FULLNODE_COLLECT_MS() { return process.env.FULLNODE_COLLECT_MS; },
    get FULLNODE_ENABLED() { return process.env.FULLNODE_ENABLED; },
    get FULLNODE_POLL_MS() { return process.env.FULLNODE_POLL_MS; },
    get FULLNODE_SPEND_LOG_PATH() { return process.env.FULLNODE_SPEND_LOG_PATH; },
    get GOVERNANCE_TALLY_INTERVAL() { return process.env.GOVERNANCE_TALLY_INTERVAL; },
    get GOV_VOTING_PERIOD() { return process.env.GOV_VOTING_PERIOD; },
    get HUB_ADMISSION_RELAY() { return process.env.HUB_ADMISSION_RELAY; },
    get HUB_ALLOW_UNAUTHENTICATED() { return process.env.HUB_ALLOW_UNAUTHENTICATED; },
    get HUB_API_KEY() { return process.env.HUB_API_KEY; },
    get HUB_CAPABILITY_CONFIG() { return process.env.HUB_CAPABILITY_CONFIG; },
    get HUB_CONFIG_SECRETS_API_KEY() { return process.env.HUB_CONFIG_SECRETS_API_KEY; },
    get HUB_CONSENSUS_INPUT_ALERT_AFTER() { return process.env.HUB_CONSENSUS_INPUT_ALERT_AFTER; },
    get HUB_DB_HOST() { return process.env.HUB_DB_HOST; },
    get HUB_DB_KEEPALIVE_INTERVAL() { return process.env.HUB_DB_KEEPALIVE_INTERVAL; },
    get HUB_DB_NAME() { return process.env.HUB_DB_NAME; },
    get HUB_DB_PORT() { return process.env.HUB_DB_PORT; },
    get HUB_DB_USER() { return process.env.HUB_DB_USER; },
    get HUB_HOST() { return process.env.HUB_HOST; },
    get HUB_MAX_RPC_BATCH() { return process.env.HUB_MAX_RPC_BATCH; },
    get HUB_NETWORK() { return process.env.HUB_NETWORK; },
    get HUB_P2P_FEED_ENABLED() { return process.env.HUB_P2P_FEED_ENABLED; },
    get HUB_PORT() { return process.env.HUB_PORT; },
    get HUB_PRICE_CAPABILITY_DERIVE() { return process.env.HUB_PRICE_CAPABILITY_DERIVE; },
    get HUB_PRICE_CAPABILITY_DERIVE_INTERVAL_S() { return process.env.HUB_PRICE_CAPABILITY_DERIVE_INTERVAL_S; },
    get HUB_PRICE_CAPABILITY_DERIVE_LOOKBACK_BLOCKS() { return process.env.HUB_PRICE_CAPABILITY_DERIVE_LOOKBACK_BLOCKS; },
    get HUB_RATE_LIMIT_EXEMPT_LOCAL() { return process.env.HUB_RATE_LIMIT_EXEMPT_LOCAL; },
    get HUB_RATE_LIMIT_RPM() { return process.env.HUB_RATE_LIMIT_RPM; },
    get HUB_REORG_API_KEY() { return process.env.HUB_REORG_API_KEY; },
    get HUB_SENSITIVE_READ_AUTH() { return process.env.HUB_SENSITIVE_READ_AUTH; },
    get HUB_SNAPSHOT_REORG_BUFFER() { return process.env.HUB_SNAPSHOT_REORG_BUFFER; },
    get HUB_TRUST_PROXY() { return process.env.HUB_TRUST_PROXY; },
    get INDEXER_COIN_CHECK() { return process.env.INDEXER_COIN_CHECK; },
    get LLM_MAX_BUDGET_USD() { return process.env.LLM_MAX_BUDGET_USD; },
    get LLM_PROVIDER_ENABLED() { return process.env.LLM_PROVIDER_ENABLED; },
    get LLM_SPEND_LOG_FALLBACK_PATH() { return process.env.LLM_SPEND_LOG_FALLBACK_PATH; },
    get LLM_SPEND_LOG_PATH() { return process.env.LLM_SPEND_LOG_PATH; },
    get MAX_DIRECT_TIP_AGE_S() { return process.env.MAX_DIRECT_TIP_AGE_S; },
    get MAX_INDEXER_LAG_BLOCKS() { return process.env.MAX_INDEXER_LAG_BLOCKS; },
    get MAX_TIP_AGE_S() { return process.env.MAX_TIP_AGE_S; },
    get MIN_VALIDATORS() { return process.env.MIN_VALIDATORS; },
    get ORACLE_ALLOW_UNVERIFIED_PAIRS() { return process.env.ORACLE_ALLOW_UNVERIFIED_PAIRS; },
    get ORACLE_BATCH_BUFFER_MAX_ROUNDS() { return process.env.ORACLE_BATCH_BUFFER_MAX_ROUNDS; },
    get ORACLE_BATCH_CATCHUP_BACKLOG_INTERVAL_MS() { return process.env.ORACLE_BATCH_CATCHUP_BACKLOG_INTERVAL_MS; },
    get ORACLE_BATCH_CATCHUP_INTERVAL_MS() { return process.env.ORACLE_BATCH_CATCHUP_INTERVAL_MS; },
    get ORACLE_BATCH_CATCHUP_MAX_ATTEMPTS() { return process.env.ORACLE_BATCH_CATCHUP_MAX_ATTEMPTS; },
    get ORACLE_BATCH_CATCHUP_RETIRE_AFTER_MS() { return process.env.ORACLE_BATCH_CATCHUP_RETIRE_AFTER_MS; },
    get ORACLE_BATCH_GRACE_MS() { return process.env.ORACLE_BATCH_GRACE_MS; },
    get ORACLE_BATCH_LANDING_RESERVE_MS() { return process.env.ORACLE_BATCH_LANDING_RESERVE_MS; },
    get ORACLE_BATCH_SIGN_TIMEOUT_MS() { return process.env.ORACLE_BATCH_SIGN_TIMEOUT_MS; },
    get ORACLE_BATCH_WINDOW_ROUNDS() { return process.env.ORACLE_BATCH_WINDOW_ROUNDS; },
    get ORACLE_CLAMP_RESEED_MS() { return process.env.ORACLE_CLAMP_RESEED_MS; },
    get ORACLE_EARLY_MSG_MAX_ROUNDS() { return process.env.ORACLE_EARLY_MSG_MAX_ROUNDS; },
    get ORACLE_EPOCH_START() { return process.env.ORACLE_EPOCH_START; },
    get ORACLE_FINALIZATION_TIMEOUT() { return process.env.ORACLE_FINALIZATION_TIMEOUT; },
    get ORACLE_FINALIZED_MAX() { return process.env.ORACLE_FINALIZED_MAX; },
    get ORACLE_LEADER_TIMEOUT_MS() { return process.env.ORACLE_LEADER_TIMEOUT_MS; },
    get ORACLE_MAX_PRICE_AGE_SECONDS() { return process.env.ORACLE_MAX_PRICE_AGE_SECONDS; },
    get ORACLE_MAX_SUBMISSIONS_PER_ROUND() { return process.env.ORACLE_MAX_SUBMISSIONS_PER_ROUND; },
    get ORACLE_MIN_SUBMISSIONS() { return process.env.ORACLE_MIN_SUBMISSIONS; },
    get ORACLE_PUBLISHED_ROUNDS_RETENTION_ROUNDS() { return process.env.ORACLE_PUBLISHED_ROUNDS_RETENTION_ROUNDS; },
    get ORACLE_PUBLISH_ALLOW_UNCONFIRMED_INPUTS() { return process.env.ORACLE_PUBLISH_ALLOW_UNCONFIRMED_INPUTS; },
    get ORACLE_PUBLISH_BLOCK_MS() { return process.env.ORACLE_PUBLISH_BLOCK_MS; },
    get ORACLE_PUBLISH_CONFIRM_CHECK_MS() { return process.env.ORACLE_PUBLISH_CONFIRM_CHECK_MS; },
    get ORACLE_PUBLISH_CONFIRM_STALE_MS() { return process.env.ORACLE_PUBLISH_CONFIRM_STALE_MS; },
    get ORACLE_PUBLISH_ENABLED() { return process.env.ORACLE_PUBLISH_ENABLED; },
    get ORACLE_PUBLISH_FAILOVER_WINDOW_BLOCKS() { return process.env.ORACLE_PUBLISH_FAILOVER_WINDOW_BLOCKS; },
    get ORACLE_PUBLISH_SELF_CHAIN_MAX_DEPTH() { return process.env.ORACLE_PUBLISH_SELF_CHAIN_MAX_DEPTH; },
    get ORACLE_REWARD_PER_ROUND() { return process.env.ORACLE_REWARD_PER_ROUND; },
    get ORACLE_ROUND_ABANDON_GRACE_MS() { return process.env.ORACLE_ROUND_ABANDON_GRACE_MS; },
    get ORACLE_ROUND_INTERVAL() { return process.env.ORACLE_ROUND_INTERVAL; },
    get ORACLE_SNAPSHOT_TOLERANCE_BLOCKS() { return process.env.ORACLE_SNAPSHOT_TOLERANCE_BLOCKS; },
    get ORACLE_STALENESS_THRESHOLD_S() { return process.env.ORACLE_STALENESS_THRESHOLD_S; },
    get ORACLE_SUBMISSIONS_RETENTION_ROUNDS() { return process.env.ORACLE_SUBMISSIONS_RETENTION_ROUNDS; },
    get ORACLE_SUBMISSION_WINDOW() { return process.env.ORACLE_SUBMISSION_WINDOW; },
    get ORACLE_TAKEOVER_AMBIGUOUS_COOLDOWN_MS() { return process.env.ORACLE_TAKEOVER_AMBIGUOUS_COOLDOWN_MS; },
    get P2P_DEDUP_PRUNE_INTERVAL() { return process.env.P2P_DEDUP_PRUNE_INTERVAL; },
    get P2P_HEARTBEAT_INTERVAL() { return process.env.P2P_HEARTBEAT_INTERVAL; },
    get P2P_HOST() { return process.env.P2P_HOST; },
    get P2P_MAX_CONNECTIONS_PER_IP() { return process.env.P2P_MAX_CONNECTIONS_PER_IP; },
    get P2P_MAX_PAYLOAD() { return process.env.P2P_MAX_PAYLOAD; },
    get P2P_MSG_DEDUP_TTL() { return process.env.P2P_MSG_DEDUP_TTL; },
    get P2P_PORT() { return process.env.P2P_PORT; },
    get P2P_RECONNECT_BASE() { return process.env.P2P_RECONNECT_BASE; },
    get P2P_RECONNECT_MAX() { return process.env.P2P_RECONNECT_MAX; },
    get P2P_SIGNER_SET_REFRESH_MS() { return process.env.P2P_SIGNER_SET_REFRESH_MS; },
    get P2P_VALIDATOR_ADDR() { return process.env.P2P_VALIDATOR_ADDR; },
    get P2P_WS_PING_INTERVAL() { return process.env.P2P_WS_PING_INTERVAL; },
    get PBFT_SNAPSHOT_TOLERANCE_BLOCKS() { return process.env.PBFT_SNAPSHOT_TOLERANCE_BLOCKS; },
    get PBFT_TIMEOUT() { return process.env.PBFT_TIMEOUT; },
    get PRICE_FETCH_TIMEOUT() { return process.env.PRICE_FETCH_TIMEOUT; },
    get PUBLISHER_MAX_ATTEMPTS() { return process.env.PUBLISHER_MAX_ATTEMPTS; },
    get PUBLISHER_QUEUE_PATH() { return process.env.PUBLISHER_QUEUE_PATH; },
    get REORG_ALLOW_UNRECORDED_OLDHASH() { return process.env.REORG_ALLOW_UNRECORDED_OLDHASH; },
    get REORG_MAX_DEPTH() { return process.env.REORG_MAX_DEPTH; },
    get REORG_MAX_LOOKBACK_MS() { return process.env.REORG_MAX_LOOKBACK_MS; },
    get REORG_MAX_PENDING() { return process.env.REORG_MAX_PENDING; },
    get REORG_TIMEOUT() { return process.env.REORG_TIMEOUT; },
    get REORG_TIMESTAMP_SKEW_MS() { return process.env.REORG_TIMESTAMP_SKEW_MS; },
    get REQUIRE_SIGNATURES() { return process.env.REQUIRE_SIGNATURES; },
    get RETRACT_INTENT_TTL_MS() { return process.env.RETRACT_INTENT_TTL_MS; },
    get RETRACT_ROUND_TIMEOUT_MS() { return process.env.RETRACT_ROUND_TIMEOUT_MS; },
    get RETRACT_SIGN_RETRY_MS() { return process.env.RETRACT_SIGN_RETRY_MS; },
    get ROLLCALL_ENABLED() { return process.env.ROLLCALL_ENABLED; },
    get ROLLCALL_POLL_MS() { return process.env.ROLLCALL_POLL_MS; },
    get ROLLCALL_SIGN_LOG_PATH() { return process.env.ROLLCALL_SIGN_LOG_PATH; },
    get ROLLCALL_SPEND_LOG_PATH() { return process.env.ROLLCALL_SPEND_LOG_PATH; },
    get SEED_NODES() { return process.env.SEED_NODES; },
    get SLASH_DEVIATION_THRESHOLD() { return process.env.SLASH_DEVIATION_THRESHOLD; },
    get SLASH_MISSED_ROUNDS_THRESHOLD() { return process.env.SLASH_MISSED_ROUNDS_THRESHOLD; },
    get TELEMETRY_ADMIN_KEY() { return process.env.TELEMETRY_ADMIN_KEY; },
    get TELEMETRY_ENABLED() { return process.env.TELEMETRY_ENABLED; },
    get TELEMETRY_IP_SALT() { return process.env.TELEMETRY_IP_SALT; },
    get TELEMETRY_RETENTION_DAYS() { return process.env.TELEMETRY_RETENTION_DAYS; },
    get WS_BACKPRESSURE_LIMIT() { return process.env.WS_BACKPRESSURE_LIMIT; },
    get WS_MAX_PER_IP() { return process.env.WS_MAX_PER_IP; },
    get WS_MAX_SUBSCRIBERS() { return process.env.WS_MAX_SUBSCRIBERS; },
    get WS_WATERMARK_INTERVAL_MS() { return process.env.WS_WATERMARK_INTERVAL_MS; },
    get WS_WATERMARK_LATE_FACTOR() { return process.env.WS_WATERMARK_LATE_FACTOR; },
    get XBRIDGE_POLL_MS() { return process.env.XBRIDGE_POLL_MS; },
    get XCALL_POLL_MS() { return process.env.XCALL_POLL_MS; },
    get XCALL_RELAY_MARGIN_BLOCKS() { return process.env.XCALL_RELAY_MARGIN_BLOCKS; },
    get XCHAIN_ATTEST_FINALIZED_MAX() { return process.env.XCHAIN_ATTEST_FINALIZED_MAX; },
    get XCHAIN_ATTEST_STORE_RETRIES() { return process.env.XCHAIN_ATTEST_STORE_RETRIES; },
    get XCHAIN_ATTEST_STORE_RETRY_MS() { return process.env.XCHAIN_ATTEST_STORE_RETRY_MS; },
    get XCHAIN_HUB_SKIP_FULLNODE_ASSERT() { return process.env.XCHAIN_HUB_SKIP_FULLNODE_ASSERT; },
    get XCHAIN_HUB_SKIP_MIN_STAKE_ASSERT() { return process.env.XCHAIN_HUB_SKIP_MIN_STAKE_ASSERT; },
    get XCHAIN_HUB_SKIP_REORG_BUFFER_ASSERT() { return process.env.XCHAIN_HUB_SKIP_REORG_BUFFER_ASSERT; },
    get XCHAIN_PRICE_BOOTSTRAP_SATS() { return process.env.XCHAIN_PRICE_BOOTSTRAP_SATS; },
    get XCHAIN_PRICE_CONFIRMATION_BUFFER() { return process.env.XCHAIN_PRICE_CONFIRMATION_BUFFER; },
    get XCHAIN_PRICE_INDEXER_DB_COIN() { return process.env.XCHAIN_PRICE_INDEXER_DB_COIN; },
    get XCHAIN_PRICE_INDEXER_DB_HOST() { return process.env.XCHAIN_PRICE_INDEXER_DB_HOST; },
    get XCHAIN_PRICE_INDEXER_DB_NAME() { return process.env.XCHAIN_PRICE_INDEXER_DB_NAME; },
    get XCHAIN_PRICE_INDEXER_DB_PORT() { return process.env.XCHAIN_PRICE_INDEXER_DB_PORT; },
    get XCHAIN_PRICE_INDEXER_DB_USER() { return process.env.XCHAIN_PRICE_INDEXER_DB_USER; },
    get XCHAIN_PRICE_MIN_BTC_VOLUME() { return process.env.XCHAIN_PRICE_MIN_BTC_VOLUME; },
    get XCHAIN_PRICE_WINDOW_BLOCKS() { return process.env.XCHAIN_PRICE_WINDOW_BLOCKS; },
    get XDEX_MIN_CONFIRMATIONS() { return process.env.XDEX_MIN_CONFIRMATIONS; },
    get XDEX_POLL_MS() { return process.env.XDEX_POLL_MS; },
    get XDEX_ROUND_MAX_LIFETIME_MS() { return process.env.XDEX_ROUND_MAX_LIFETIME_MS; },
    get XDEX_ROUND_TIMEOUT_MS() { return process.env.XDEX_ROUND_TIMEOUT_MS; },
    get XDEX_SEED_LOCAL_VALIDATOR() { return process.env.XDEX_SEED_LOCAL_VALIDATOR; },
    get XDEX_SNAPSHOT_BLOCK() { return process.env.XDEX_SNAPSHOT_BLOCK; },
};

/**
 * Return the environment OBJECT a caller should read, for the shapes a named
 * getter cannot carry: a computed key, a spread, or a default for an injected env.
 *
 * Contract, which every rewritten site relies on:
 * - Reads at CALL time. Nothing is cached, so a test that sets or replaces
 *   process.env between cases is seen by the next call.
 * - `config.env(injected)` is exactly `injected || process.env`: a truthy
 *   injected env (a test seam, a ctx.env) wins and is returned as-is, and an
 *   absent one (undefined, null) falls back to the live process.env.
 * - Returns process.env ITSELF, not a copy, so identity, `in`, spreads and
 *   later mutations behave as before. Callers read through it; they do not write.
 * - Precedence stays at the site: `config.env()[k] || cfg[k] || ''` keeps the
 *   env-over-cfg order and the default exactly where the site had them.
 * - Throws TypeError when `injected` is truthy but not an object, the shape of
 *   a mistaken `config.env('BTC_INDEXER_URL')`. The message names the type
 *   only, never the value, since an env value may be a credential.
 *
 * Rewrites: `process.env[coin + '_INDEXER_URL']` -> `config.env()[coin + '_INDEXER_URL']`;
 * `opts.env || process.env` -> `config.env(opts.env)`; `{ ...process.env }` ->
 * `{ ...config.env() }`; a parameter default `env = process.env` -> `env = config.env()`.
 *
 * @param {object} [injected] env-shaped object the caller was handed
 * @returns {object} injected when truthy, else the live process.env
 * @throws {TypeError} injected is truthy and not an object
 */
function env(injected) {
    if (!injected) return process.env;
    if (typeof injected !== 'object') {
        throw new TypeError('config.env: an injected env must be an object, got ' + typeof injected);
    }
    return injected;
}

// Attached outside the literal and non-enumerable: the object's own keys stay the
// variable inventory, and the env-config codemod still reads it as a lazy home.
Object.defineProperty(config, 'env', { value: env, enumerable: false });

Object.freeze(config);

module.exports = config;
